name: Build Windows Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: 🛠 Install vcpkg dependencies
        run: |
          if not exist C:\vcpkg (
            echo Cloning vcpkg...
            git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          )
          if not exist C:\vcpkg\bootstrap-vcpkg.bat (
            echo Bootstrapping vcpkg...
            C:\vcpkg\bootstrap-vcpkg.bat
          )
          echo Updating vcpkg...
          C:\vcpkg\vcpkg integrate install
          C:\vcpkg\vcpkg update || echo vcpkg already up to date.
          C:\vcpkg\vcpkg upgrade --no-dry-run || echo No upgrades needed.
          echo Installing dependencies...
          C:\vcpkg\vcpkg install fmt openssl curl[openssl] spdlog zlib libsodium nlohmann-json boost-program-options --triplet x86-windows-static
        shell: cmd

      - name: 🔍 Extract Version from .rc File
        id: get_version
        run: |
          $version = (Select-String -Path "ServiceUpdater/ServiceUpdater.rc" -Pattern "FILEVERSION\s+(\d+),\s*(\d+),\s*(\d+),\s*(\d+)").Matches.Groups[1..4] -join "."
          echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: pwsh

      - name: 🏗 Build Solution
        run: msbuild ServiceUpdater.sln /p:Configuration=Release /p:Platform=x86 /m /t:Rebuild /p:VcpkgRoot=C:\vcpkg
        shell: cmd

      - name: 🔍 Debug Build Output
        run: |
          echo "Checking Release directory contents:"
          Get-ChildItem -Path "Release\" -Recurse
        shell: pwsh

      - name: 📁 Organize Build Artifacts
        run: |
          mkdir Builds
          mkdir Builds\ServiceUpdater_v${{ env.APP_VERSION }}
          Copy-Item -Path "Release\ServiceUpdater.exe" -Destination "Builds/ServiceUpdater_v${{ env.APP_VERSION }}" -Force
        shell: pwsh

      - name: 📦 Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ServiceUpdater_v${{ env.APP_VERSION }}
          path: Builds/ServiceUpdater_v${{ env.APP_VERSION }}
